name: General Issue
description: Dieses Issue soll f체r beliebige Arbeitsauftr채ge dienen.
title: "Bitte 채ndern..."
projects: ["HisQu/1"]
body:
  - type: markdown
    attributes:
      value: |
        Dieses Issue wird automatisch dem Projekt HisQu zugeordnet.
  - type: textarea
    id: what-happened
    attributes:
      label: Aufgabe
      description: Was ist die zu erledigende Aufgabe? Bitte mgl. verst채ndlich spezifizieren.
      placeholder: Arbeitsauftrag hier
      value: "..."
    validations:
      required: true
