name: General Issue
description: 
title: "Bitte ändern..."
projects: ["HisQu/1"]
body:
  - type: markdown
    attributes:
      value: |
        Dieses Issue wird automatisch dem Projekt HisQu zugeordnet.
  - type: textarea
    id: what-happened
    attributes:
      label: Aufgabe
      description: Was ist die zu erledigende Aufgabe? Bitte mgl. verständlich spezifizieren.
      placeholder: Arbeitsauftrag hier
      value: "..."
    validations:
      required: true
