# This workflow adds new issues to the HisQu project.

name: Add New Issue to HisQu Project
on:
  issues:
    types: [opened] # This action only runs when a new issue is opened

jobs:
  add-to-project:
    name: Add Issue to project
    runs-on: ubuntu-latest
    permissions:
      # This permission allows the action to access issue data (like its ID)
      # and potentially make changes if the action needed to (though add-to-project primarily reads the issue).
      issues: write # Or issues: read might be sufficient if the action only needs to read issue data. Start with 'write' for safety.
      
      # For GITHUB_TOKEN to modify an organization-level project (Classic or V2),
      # your organization settings must allow GitHub Actions to manage projects.
      # Since your PR workflow works with GITHUB_TOKEN, it's likely these settings are permissive enough.

    steps:
      - name: Add issue to the HisQu project
        uses: actions/add-to-project@v1.0.1 # Using the same version as your working PR script
        with:
          # The URL of your project.
          project-url: "https://github.com/orgs/HisQu/projects/1" # Same as your PR script
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Optional: If you want to add the issue to a specific column:
          # column-name: "To Do" 
