name: Auto Set Project Status to Done on Close

on:
  issues:
    types:
      - closed
  pull_request:
    types:
      - closed
      - merged

jobs:
  update-project-status:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read # Changed to read, write not strictly needed for this workflow
      pull-requests: read # Changed to read, write not strictly needed for this workflow
      # No 'projects: write' here, relying on PAT scopes as discussed

    steps:
      - name: Get Issue/PR Node ID, Repo Info, and Project ID
        id: get_initial_ids # Renamed ID for clarity
        env:
          ORG_NAME: HisQu
          PROJECT_TITLE: HisQu
          GITHUB_TOKEN: ${{ secrets.ORG_SYNC_PAT }}
        run: |
          ITEM_CONTENT_ID="" # This will store the global ID of the Issue/PR
          REPO_NAME=""
          REPO_OWNER=""

          if [[ "${{ github.event_name }}" == "issues" ]]; then
            ITEM_CONTENT_ID="${{ github.event.issue.node_id }}"
            REPO_NAME="${{ github.event.repository.name }}"
            REPO_OWNER="${{ github.event.repository.owner.login }}"
            echo "Processing issue: ${{ github.event.issue.html_url }}"
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            ITEM_CONTENT_ID="${{ github.event.pull_request.node_id }}"
            REPO_NAME="${{ github.event.repository.name }}"
            REPO_OWNER="${{ github.event.repository.owner.login }}"
            echo "Processing pull request: ${{ github.event.pull_request.html_url }}"
          fi

          echo "ITEM_CONTENT_ID=$ITEM_CONTENT_ID" >> $GITHUB_OUTPUT
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_OUTPUT
          echo "REPO_OWNER=$REPO_OWNER" >> $GITHUB_OUTPUT

          PROJECT_RESPONSE=$(curl -s -L \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            https://api.github.com/graphql \
            -d '{
              "query": "query($org: String!, $projectTitle: String!) { organization(login: $org) { projectsV2(query: $projectTitle, first: 1) { nodes { id title } } } }",
              "variables": {
                "org": "'"$ORG_NAME"'",
                "projectTitle": "'"$PROJECT_TITLE"'"
              }
            }')

          PROJECT_ID=$(echo "$PROJECT_RESPONSE" | jq -r '.data.organization.projectsV2.nodes[0].id')
          if [ "$PROJECT_ID" == "null" ]; then
            echo "Error: Project with title '$PROJECT_TITLE' not found in organization '$ORG_NAME'."
            exit 1
          fi
          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_OUTPUT
          echo "Found Project ID: $PROJECT_ID"

      # --- STEP TO GET THE PROJECT ITEM ID ---
      - name: Get Project V2 Item ID for the Issue/PR
        id: get_project_item_id
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_SYNC_PAT }}
          PROJECT_ID: ${{ steps.get_initial_ids.outputs.PROJECT_ID }}
          ITEM_CONTENT_ID: ${{ steps.get_initial_ids.outputs.ITEM_CONTENT_ID }}
          REPO_NAME: ${{ steps.get_initial_ids.outputs.REPO_NAME }}
          REPO_OWNER: ${{ steps.get_initial_ids.outputs.REPO_OWNER }}
        run: |
          echo "Attempting to find item with content ID: $ITEM_CONTENT_ID in project: $PROJECT_ID for repo: $REPO_OWNER/$REPO_NAME"

          PROJECT_ITEMS_RESPONSE=$(curl -s -L \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            https://api.github.com/graphql \
            -d '{
              "query": "query($projectId: ID!) { node(id: $projectId) { ... on ProjectV2 { items(first: 100) { nodes { id content { ... on Issue { id number repository { nameWithOwner } } ... on PullRequest { id number repository { nameWithOwner } } } } } } } }",
              "variables": {
                "projectId": "'"$PROJECT_ID"'"
              }
            }')

          echo "GraphQL Response for Project Items:"
          echo "$PROJECT_ITEMS_RESPONSE" # Log the response for debugging

          # Check for GraphQL errors
          if echo "$PROJECT_ITEMS_RESPONSE" | jq -e '.errors' > /dev/null; then
            echo "Error: GraphQL query for project items failed:"
            echo "$PROJECT_ITEMS_RESPONSE" | jq '.errors'
            exit 1
          fi

          # Check if the expected path exists before trying to iterate
          if ! echo "$PROJECT_ITEMS_RESPONSE" | jq -e '.data.node.items.nodes' > /dev/null; then
            echo "Error: '.data.node.items.nodes' path not found or is null in GraphQL response."
            echo "This could mean the project ID is invalid, has no items, or there was an API issue."
            exit 1
          fi
          
          # If nodes is null (but items exists), treat as empty to avoid jq error
          # This handles cases where a project exists but has 0 items.
          PROJECT_ITEM_ID=$(echo "$PROJECT_ITEMS_RESPONSE" | jq -r --arg ITEM_CONTENT_ID "$ITEM_CONTENT_ID" --arg REPO_FULL_NAME "$REPO_OWNER/$REPO_NAME" \
            '.data.node.items.nodes[]? | select(.content != null and .content.id == $ITEM_CONTENT_ID and .content.repository.nameWithOwner == $REPO_FULL_NAME) | .id // empty')

          if [ -z "$PROJECT_ITEM_ID" ]; then
            echo "Warning: Could not find ProjectV2Item ID for content ID '$ITEM_CONTENT_ID' from repo '$REPO_OWNER/$REPO_NAME' in project '$PROJECT_ID'. The issue/PR might not be in the project, or the lookup query failed."
            # Decide if this should be a failure or a graceful exit.
            # For your use case, `exit 0` seems correct if the item not being in the project is acceptable.
            exit 0 
          fi
          
          echo "PROJECT_ITEM_ID=$PROJECT_ITEM_ID" >> $GITHUB_OUTPUT
          echo "Found ProjectV2Item ID: $PROJECT_ITEM_ID"

      - name: Get Project Status Field ID and Option ID for "Done"
        id: get_field_ids
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_SYNC_PAT }}
          PROJECT_ID: ${{ steps.get_initial_ids.outputs.PROJECT_ID }}
        run: |
          # ... (rest of this step - no change)
          FIELD_RESPONSE=$(curl -s -L \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            https://api.github.com/graphql \
            -d '{
              "query": "query($projectId: ID!) { node(id: $projectId) { ... on ProjectV2 { fields(first: 20) { nodes { ... on ProjectV2Field { id name } ... on ProjectV2SingleSelectField { id name options { id name } } } } } } }",
              "variables": {
                "projectId": "'"$PROJECT_ID"'"
              }
            }')

          STATUS_FIELD_ID=$(echo "$FIELD_RESPONSE" | jq -r '.data.node.fields.nodes[] | select(.name == "Status") | .id')
          DONE_OPTION_ID=$(echo "$FIELD_RESPONSE" | jq -r '.data.node.fields.nodes[] | select(.name == "Status") | .options[] | select(.name == "Done") | .id')

          if [ "$STATUS_FIELD_ID" == "null" ]; then
            echo "Error: 'Status' field not found in project."
            exit 1
          fi
          if [ "$DONE_OPTION_ID" == "null" ]; then
            echo "Error: 'Done' option not found in 'Status' field."
            exit 1
          fi

          echo "STATUS_FIELD_ID=$STATUS_FIELD_ID" >> $GITHUB_OUTPUT
          echo "DONE_OPTION_ID=$DONE_OPTION_ID" >> $GITHUB_OUTPUT
          echo "Found Status Field ID: $STATUS_FIELD_ID, Done Option ID: $DONE_OPTION_ID"

      - name: Update Project Item Status to "Done"
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ORG_SYNC_PAT }}
          script: |
            const projectId = "${{ steps.get_initial_ids.outputs.PROJECT_ID }}";
            const projectItemId = "${{ steps.get_project_item_id.outputs.PROJECT_ITEM_ID }}"; // <-- USE PROJECT_ITEM_ID HERE
            const statusFieldId = "${{ steps.get_field_ids.outputs.STATUS_FIELD_ID }}";
            const doneOptionId = "${{ steps.get_field_ids.outputs.DONE_OPTION_ID }}";

            if (!projectItemId) { // Check for projectItemId, not itemNodeId
              core.info('Project item ID not found. Skipping status update.');
              return;
            }

            try {
              await github.graphql(`
                mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) { # itemId instead of itemNodeId
                  updateProjectV2ItemFieldValue(input: {
                    projectId: $projectId,
                    itemId: $itemId, # <-- This is the key change here
                    fieldId: $fieldId,
                    value: {
                      singleSelectOptionId: $optionId
                    }
                  }) {
                    projectV2Item {
                      id
                    }
                  }
                }`, {
                projectId: projectId,
                itemId: projectItemId, // <-- Pass the ProjectV2Item's ID
                fieldId: statusFieldId,
                optionId: doneOptionId
              });
              core.info(`Successfully set status of ${{ github.event_name }} to "Done" in project.`);
            } catch (error) {
              // The error message "Could not resolve to a ProjectV2Item with the ID"
              // should now be caught by the new 'get_project_item_id' step's check,
              // or indicate a different issue.
              core.error(`Failed to update status to "Done" for ${{ github.event_name }}: ${error.message}`);
              core.setFailed(`Failed to update status to "Done" for ${{ github.event_name }}: ${error.message}`);
            }
