name: Generate TOC
on:
  push:
    branches:
      - main # default branch
    paths:
      - 'README.md'
jobs:
  generate-toc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate TOC
        run: |
          npx markdown-toc -i README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: update TOC in README.md"
          file_pattern: README.md
